2022-03-08 01:02:32,542 INFO    MainThread:3014 [wandb_setup.py:_flush():75] Loading settings from /home/lieberze/.config/wandb/settings
2022-03-08 01:02:32,542 INFO    MainThread:3014 [wandb_setup.py:_flush():75] Loading settings from /home/lieberze/DP/Thesis/06_adapter/wandb/settings
2022-03-08 01:02:32,542 INFO    MainThread:3014 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-08 01:02:32,542 INFO    MainThread:3014 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-08 01:02:32,543 INFO    MainThread:3014 [wandb_init.py:_log_setup():386] Logging user logs to /home/lieberze/DP/Thesis/06_adapter/wandb/run-20220308_010232-1cdidnu0/logs/debug.log
2022-03-08 01:02:32,543 INFO    MainThread:3014 [wandb_init.py:_log_setup():387] Logging internal logs to /home/lieberze/DP/Thesis/06_adapter/wandb/run-20220308_010232-1cdidnu0/logs/debug-internal.log
2022-03-08 01:02:32,543 INFO    MainThread:3014 [wandb_init.py:_jupyter_setup():336] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fae1a1946d8>
2022-03-08 01:02:32,544 INFO    MainThread:3014 [wandb_init.py:init():420] calling init triggers
2022-03-08 01:02:32,544 INFO    MainThread:3014 [wandb_init.py:init():427] wandb.init called with sweep_config: {}
config: {}
2022-03-08 01:02:32,544 INFO    MainThread:3014 [wandb_init.py:init():442] re-initializing run, found existing run on stack: 3m8wo99a
2022-03-08 01:02:32,547 INFO    MainThread:3014 [wandb_run.py:finish():1468] finishing run liebelife/adapter_CV_3x3/3m8wo99a
2022-03-08 01:02:32,547 INFO    MainThread:3014 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-03-08 01:02:32,552 INFO    MainThread:3014 [wandb_run.py:_restore():1769] restore
2022-03-08 01:02:33,253 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 880
}

2022-03-08 01:02:33,448 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 880
}

2022-03-08 01:02:33,651 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 880
}

2022-03-08 01:02:34,262 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 12764
}

2022-03-08 01:02:34,367 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 12764
}

2022-03-08 01:02:34,475 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 12764
}

2022-03-08 01:02:34,577 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12764
  total_bytes: 12764
}

2022-03-08 01:02:34,682 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12764
  total_bytes: 12764
}

2022-03-08 01:02:34,785 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12764
  total_bytes: 12764
}

2022-03-08 01:02:34,887 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12764
  total_bytes: 12764
}

2022-03-08 01:02:34,990 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12764
  total_bytes: 12764
}

2022-03-08 01:02:35,092 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12764
  total_bytes: 12764
}

2022-03-08 01:02:36,212 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12764
  total_bytes: 12764
}

2022-03-08 01:02:36,647 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12764
  total_bytes: 12764
}
local_info {
}

2022-03-08 01:02:38,111 INFO    MainThread:3014 [wandb_run.py:_append_files():2194] logging synced files
2022-03-08 01:02:38,121 INFO    MainThread:3014 [wandb_init.py:init():471] starting backend
2022-03-08 01:02:38,121 INFO    MainThread:3014 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-08 01:02:38,125 INFO    MainThread:3014 [backend.py:ensure_launched():219] starting backend process...
2022-03-08 01:02:38,230 INFO    MainThread:3014 [backend.py:ensure_launched():225] started backend process with pid: 5506
2022-03-08 01:02:38,231 INFO    MainThread:3014 [wandb_init.py:init():480] backend started and connected
2022-03-08 01:02:38,258 INFO    MainThread:3014 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-03-08 01:02:38,259 INFO    MainThread:3014 [wandb_run.py:_label_probe_notebook():931] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-03-08 01:02:38,259 INFO    MainThread:3014 [wandb_init.py:init():550] updated telemetry
2022-03-08 01:02:38,473 INFO    MainThread:3014 [wandb_init.py:init():581] communicating current version
2022-03-08 01:02:39,787 INFO    MainThread:3014 [wandb_init.py:init():586] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-08 01:02:39,789 INFO    MainThread:3014 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-08 01:02:40,068 INFO    MainThread:3014 [wandb_init.py:init():624] starting run threads in backend
2022-03-08 01:02:45,080 INFO    MainThread:3014 [wandb_run.py:_console_start():1827] atexit reg
2022-03-08 01:02:45,081 INFO    MainThread:3014 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2022-03-08 01:02:45,082 INFO    MainThread:3014 [wandb_run.py:_redirect():1738] Wrapping output streams.
2022-03-08 01:02:45,083 INFO    MainThread:3014 [wandb_run.py:_redirect():1762] Redirects installed.
2022-03-08 01:02:45,083 INFO    MainThread:3014 [wandb_init.py:init():651] run started, returning control to user process
2022-03-08 01:02:46,486 INFO    MainThread:3014 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-08 01:02:46,487 INFO    MainThread:3014 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-08 01:13:03,504 INFO    MainThread:3014 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-08 01:13:03,539 INFO    MainThread:3014 [wandb_setup.py:_flush():75] Loading settings from /home/lieberze/.config/wandb/settings
2022-03-08 01:13:03,539 INFO    MainThread:3014 [wandb_setup.py:_flush():75] Loading settings from /home/lieberze/DP/Thesis/06_adapter/wandb/settings
2022-03-08 01:13:03,539 INFO    MainThread:3014 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-08 01:13:03,539 INFO    MainThread:3014 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-08 01:13:03,539 INFO    MainThread:3014 [wandb_init.py:_log_setup():386] Logging user logs to /home/lieberze/DP/Thesis/06_adapter/wandb/run-20220308_011303-qivknk94/logs/debug.log
2022-03-08 01:13:03,540 INFO    MainThread:3014 [wandb_init.py:_log_setup():387] Logging internal logs to /home/lieberze/DP/Thesis/06_adapter/wandb/run-20220308_011303-qivknk94/logs/debug-internal.log
2022-03-08 01:13:03,540 INFO    MainThread:3014 [wandb_init.py:init():420] calling init triggers
2022-03-08 01:13:03,540 INFO    MainThread:3014 [wandb_init.py:init():427] wandb.init called with sweep_config: {}
config: {}
2022-03-08 01:13:03,540 INFO    MainThread:3014 [wandb_init.py:init():442] re-initializing run, found existing run on stack: 1cdidnu0
2022-03-08 01:13:03,543 INFO    MainThread:3014 [wandb_run.py:finish():1468] finishing run liebelife/adapter_CV_3x3/1cdidnu0
2022-03-08 01:13:03,544 INFO    MainThread:3014 [jupyter.py:save_history():429] not saving jupyter history
2022-03-08 01:13:03,544 INFO    MainThread:3014 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-08 01:13:03,544 INFO    MainThread:3014 [wandb_init.py:_jupyter_teardown():318] cleaning up jupyter logic
2022-03-08 01:13:03,544 INFO    MainThread:3014 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-03-08 01:13:03,549 INFO    MainThread:3014 [wandb_run.py:_restore():1769] restore
2022-03-08 01:13:04,301 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 880
}

2022-03-08 01:13:04,424 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 880
}

2022-03-08 01:13:04,641 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 880
}

2022-03-08 01:13:04,802 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 12763
}

2022-03-08 01:13:04,907 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 12763
}

2022-03-08 01:13:05,011 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 12763
}

2022-03-08 01:13:05,113 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12763
  total_bytes: 12763
}

2022-03-08 01:13:05,218 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12763
  total_bytes: 12763
}

2022-03-08 01:13:05,320 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12763
  total_bytes: 12763
}

2022-03-08 01:13:05,423 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12763
  total_bytes: 12763
}

2022-03-08 01:13:05,525 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12763
  total_bytes: 12763
}

2022-03-08 01:13:05,628 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12763
  total_bytes: 12763
}

2022-03-08 01:13:06,501 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12763
  total_bytes: 12763
}

2022-03-08 01:13:06,961 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12763
  total_bytes: 12763
}
local_info {
}

2022-03-08 01:13:08,420 INFO    MainThread:3014 [wandb_run.py:_append_files():2194] logging synced files
