2022-03-10 00:17:24,001 INFO    MainThread:7405 [wandb_setup.py:_flush():75] Loading settings from /home/lieberze/.config/wandb/settings
2022-03-10 00:17:24,001 INFO    MainThread:7405 [wandb_setup.py:_flush():75] Loading settings from /home/lieberze/DP/Thesis/06_adapter/wandb/settings
2022-03-10 00:17:24,001 INFO    MainThread:7405 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-10 00:17:24,001 INFO    MainThread:7405 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-10 00:17:24,001 INFO    MainThread:7405 [wandb_init.py:_log_setup():386] Logging user logs to /home/lieberze/DP/Thesis/06_adapter/wandb/run-20220310_001723-35k4p1fw/logs/debug.log
2022-03-10 00:17:24,002 INFO    MainThread:7405 [wandb_init.py:_log_setup():387] Logging internal logs to /home/lieberze/DP/Thesis/06_adapter/wandb/run-20220310_001723-35k4p1fw/logs/debug-internal.log
2022-03-10 00:17:24,002 INFO    MainThread:7405 [wandb_init.py:_jupyter_setup():336] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f33c008f550>
2022-03-10 00:17:24,003 INFO    MainThread:7405 [wandb_init.py:init():420] calling init triggers
2022-03-10 00:17:24,003 INFO    MainThread:7405 [wandb_init.py:init():427] wandb.init called with sweep_config: {}
config: {}
2022-03-10 00:17:24,003 INFO    MainThread:7405 [wandb_init.py:init():471] starting backend
2022-03-10 00:17:24,003 INFO    MainThread:7405 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-10 00:17:24,016 INFO    MainThread:7405 [backend.py:ensure_launched():219] starting backend process...
2022-03-10 00:17:24,040 INFO    MainThread:7405 [backend.py:ensure_launched():225] started backend process with pid: 7431
2022-03-10 00:17:24,041 INFO    MainThread:7405 [wandb_init.py:init():480] backend started and connected
2022-03-10 00:17:24,063 INFO    MainThread:7405 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-03-10 00:17:24,064 INFO    MainThread:7405 [wandb_run.py:_label_probe_notebook():931] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-03-10 00:17:24,064 INFO    MainThread:7405 [wandb_init.py:init():550] updated telemetry
2022-03-10 00:17:24,097 INFO    MainThread:7405 [wandb_init.py:init():581] communicating current version
2022-03-10 00:17:25,577 INFO    MainThread:7405 [wandb_init.py:init():586] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-10 00:17:25,580 INFO    MainThread:7405 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-10 00:17:25,777 INFO    MainThread:7405 [wandb_init.py:init():624] starting run threads in backend
2022-03-10 00:17:30,791 INFO    MainThread:7405 [wandb_run.py:_console_start():1827] atexit reg
2022-03-10 00:17:30,792 INFO    MainThread:7405 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2022-03-10 00:17:30,796 INFO    MainThread:7405 [wandb_run.py:_redirect():1738] Wrapping output streams.
2022-03-10 00:17:30,798 INFO    MainThread:7405 [wandb_run.py:_redirect():1762] Redirects installed.
2022-03-10 00:17:30,798 INFO    MainThread:7405 [wandb_init.py:init():651] run started, returning control to user process
2022-03-10 00:17:32,167 INFO    MainThread:7405 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-10 00:17:32,167 INFO    MainThread:7405 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-10 14:21:30,233 INFO    MainThread:7405 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-10 14:21:30,235 INFO    MainThread:7405 [wandb_run.py:finish():1468] finishing run liebelife/adapter_CV_2x2/35k4p1fw
2022-03-10 14:21:30,240 INFO    MainThread:7405 [jupyter.py:save_history():429] not saving jupyter history
2022-03-10 14:21:30,240 INFO    MainThread:7405 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-10 14:21:30,241 INFO    MainThread:7405 [wandb_init.py:_jupyter_teardown():318] cleaning up jupyter logic
2022-03-10 14:21:30,241 INFO    MainThread:7405 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-03-10 14:21:30,245 INFO    MainThread:7405 [wandb_run.py:_restore():1769] restore
2022-03-10 14:21:30,898 INFO    MainThread:7405 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 880
}

2022-03-10 14:21:31,058 INFO    MainThread:7405 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 880
}

2022-03-10 14:21:31,307 INFO    MainThread:7405 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 880
}

2022-03-10 14:21:31,945 INFO    MainThread:7405 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 10690
}

2022-03-10 14:21:32,050 INFO    MainThread:7405 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 10690
}

2022-03-10 14:21:32,167 INFO    MainThread:7405 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 10690
}

2022-03-10 14:21:32,269 INFO    MainThread:7405 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10690
  total_bytes: 10690
}

2022-03-10 14:21:32,374 INFO    MainThread:7405 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10690
  total_bytes: 10690
}

2022-03-10 14:21:32,476 INFO    MainThread:7405 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10690
  total_bytes: 10690
}

2022-03-10 14:21:32,578 INFO    MainThread:7405 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10690
  total_bytes: 10690
}

2022-03-10 14:21:32,680 INFO    MainThread:7405 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10690
  total_bytes: 10690
}

2022-03-10 14:21:32,783 INFO    MainThread:7405 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10690
  total_bytes: 10690
}

2022-03-10 14:21:33,340 INFO    MainThread:7405 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10690
  total_bytes: 10690
}

2022-03-10 14:21:33,777 INFO    MainThread:7405 [wandb_run.py:_wait_for_finish():1929] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10690
  total_bytes: 10690
}
local_info {
}

2022-03-10 14:21:35,166 INFO    MainThread:7405 [wandb_run.py:_append_files():2194] logging synced files
