2022-03-07 18:31:14,349 INFO    MainThread:47862 [wandb_setup.py:_flush():75] Loading settings from /home/lieberze/.config/wandb/settings
2022-03-07 18:31:14,350 INFO    MainThread:47862 [wandb_setup.py:_flush():75] Loading settings from /home/lieberze/DP/Thesis/06_adapter/wandb/settings
2022-03-07 18:31:14,350 INFO    MainThread:47862 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-07 18:31:14,350 INFO    MainThread:47862 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-07 18:31:14,350 INFO    MainThread:47862 [wandb_init.py:_log_setup():386] Logging user logs to /home/lieberze/DP/Thesis/06_adapter/wandb/run-20220307_183114-rpowsv55/logs/debug.log
2022-03-07 18:31:14,350 INFO    MainThread:47862 [wandb_init.py:_log_setup():387] Logging internal logs to /home/lieberze/DP/Thesis/06_adapter/wandb/run-20220307_183114-rpowsv55/logs/debug-internal.log
2022-03-07 18:31:14,351 INFO    MainThread:47862 [wandb_init.py:init():420] calling init triggers
2022-03-07 18:31:14,351 INFO    MainThread:47862 [wandb_init.py:init():427] wandb.init called with sweep_config: {}
config: {}
2022-03-07 18:31:14,351 INFO    MainThread:47862 [wandb_init.py:init():442] re-initializing run, found existing run on stack: yknrmx73
2022-03-07 18:31:14,354 INFO    MainThread:47862 [wandb_run.py:finish():1468] finishing run liebelife/adapter_CV_3x3/yknrmx73
2022-03-07 18:31:14,355 INFO    MainThread:47862 [jupyter.py:save_history():429] not saving jupyter history
2022-03-07 18:31:14,355 INFO    MainThread:47862 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-07 18:31:14,355 INFO    MainThread:47862 [wandb_init.py:_jupyter_teardown():318] cleaning up jupyter logic
2022-03-07 18:31:14,355 INFO    MainThread:47862 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-03-07 18:31:14,364 INFO    MainThread:47862 [wandb_run.py:_restore():1769] restore
2022-03-07 18:31:14,958 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 880
}

2022-03-07 18:31:15,093 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 880
}

2022-03-07 18:31:15,403 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 880
}

2022-03-07 18:31:16,210 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 28242
}

2022-03-07 18:31:16,321 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 28242
}

2022-03-07 18:31:16,427 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 28242
}

2022-03-07 18:31:16,529 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28242
  total_bytes: 28242
}

2022-03-07 18:31:16,633 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28242
  total_bytes: 28242
}

2022-03-07 18:31:16,735 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28242
  total_bytes: 28242
}

2022-03-07 18:31:16,838 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28242
  total_bytes: 28242
}

2022-03-07 18:31:16,940 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28242
  total_bytes: 28242
}

2022-03-07 18:31:17,485 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28242
  total_bytes: 28242
}

2022-03-07 18:31:17,904 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28242
  total_bytes: 28242
}
local_info {
}

2022-03-07 18:31:19,482 INFO    MainThread:47862 [wandb_run.py:_append_history():2144] rendering history
2022-03-07 18:31:19,483 INFO    MainThread:47862 [wandb_run.py:_append_summary():2102] rendering summary
2022-03-07 18:31:19,483 INFO    MainThread:47862 [wandb_run.py:_append_files():2194] logging synced files
2022-03-07 18:31:19,494 INFO    MainThread:47862 [wandb_init.py:init():471] starting backend
2022-03-07 18:31:19,495 INFO    MainThread:47862 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-07 18:31:19,496 INFO    MainThread:47862 [backend.py:ensure_launched():219] starting backend process...
2022-03-07 18:31:19,569 INFO    MainThread:47862 [backend.py:ensure_launched():225] started backend process with pid: 743
2022-03-07 18:31:19,571 INFO    MainThread:47862 [wandb_init.py:init():480] backend started and connected
2022-03-07 18:31:19,604 INFO    MainThread:47862 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-03-07 18:31:19,605 INFO    MainThread:47862 [wandb_run.py:_label_probe_notebook():931] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-03-07 18:31:19,605 INFO    MainThread:47862 [wandb_init.py:init():550] updated telemetry
2022-03-07 18:31:19,833 INFO    MainThread:47862 [wandb_init.py:init():581] communicating current version
2022-03-07 18:31:21,672 INFO    MainThread:47862 [wandb_init.py:init():586] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-07 18:31:21,674 INFO    MainThread:47862 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-07 18:31:21,911 INFO    MainThread:47862 [wandb_init.py:init():624] starting run threads in backend
2022-03-07 18:31:26,922 INFO    MainThread:47862 [wandb_run.py:_console_start():1827] atexit reg
2022-03-07 18:31:26,923 INFO    MainThread:47862 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2022-03-07 18:31:26,923 INFO    MainThread:47862 [wandb_run.py:_redirect():1738] Wrapping output streams.
2022-03-07 18:31:26,924 INFO    MainThread:47862 [wandb_run.py:_redirect():1762] Redirects installed.
2022-03-07 18:31:26,925 INFO    MainThread:47862 [wandb_init.py:init():651] run started, returning control to user process
2022-03-07 18:31:55,213 INFO    MainThread:47862 [wandb_setup.py:_flush():75] Loading settings from /home/lieberze/.config/wandb/settings
2022-03-07 18:31:55,213 INFO    MainThread:47862 [wandb_setup.py:_flush():75] Loading settings from /home/lieberze/DP/Thesis/06_adapter/wandb/settings
2022-03-07 18:31:55,213 INFO    MainThread:47862 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-07 18:31:55,213 INFO    MainThread:47862 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-07 18:31:55,214 INFO    MainThread:47862 [wandb_init.py:_log_setup():386] Logging user logs to /home/lieberze/DP/Thesis/06_adapter/wandb/run-20220307_183155-2xhbgljr/logs/debug.log
2022-03-07 18:31:55,214 INFO    MainThread:47862 [wandb_init.py:_log_setup():387] Logging internal logs to /home/lieberze/DP/Thesis/06_adapter/wandb/run-20220307_183155-2xhbgljr/logs/debug-internal.log
2022-03-07 18:31:55,214 INFO    MainThread:47862 [wandb_init.py:_jupyter_setup():336] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f5c100e0f28>
2022-03-07 18:31:55,215 INFO    MainThread:47862 [wandb_init.py:init():420] calling init triggers
2022-03-07 18:31:55,215 INFO    MainThread:47862 [wandb_init.py:init():427] wandb.init called with sweep_config: {}
config: {}
2022-03-07 18:31:55,215 INFO    MainThread:47862 [wandb_init.py:init():442] re-initializing run, found existing run on stack: rpowsv55
2022-03-07 18:31:55,218 INFO    MainThread:47862 [wandb_run.py:finish():1468] finishing run liebelife/adapter_CV_3x3/rpowsv55
2022-03-07 18:31:55,218 INFO    MainThread:47862 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-03-07 18:31:55,220 INFO    MainThread:47862 [wandb_run.py:_restore():1769] restore
2022-03-07 18:31:55,982 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 880
}

2022-03-07 18:31:56,171 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 880
}

2022-03-07 18:31:56,368 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 880
}

2022-03-07 18:31:56,994 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 9304
}

2022-03-07 18:31:57,099 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 11857
}

2022-03-07 18:31:57,202 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 11857
}

2022-03-07 18:31:57,305 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 8717
  total_bytes: 11857
}

2022-03-07 18:31:57,409 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11857
  total_bytes: 11857
}

2022-03-07 18:31:57,513 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11857
  total_bytes: 11857
}

2022-03-07 18:31:57,615 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11857
  total_bytes: 11857
}

2022-03-07 18:31:57,718 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11857
  total_bytes: 11857
}

2022-03-07 18:31:57,820 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11857
  total_bytes: 11857
}

2022-03-07 18:31:58,177 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11857
  total_bytes: 11857
}

2022-03-07 18:31:58,674 INFO    MainThread:47862 [wandb_run.py:_wait_for_finish():1929] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11857
  total_bytes: 11857
}
local_info {
}

2022-03-07 18:32:00,198 INFO    MainThread:47862 [wandb_run.py:_append_files():2194] logging synced files
