2022-03-10 00:15:50,045 INFO    MainThread:7301 [wandb_setup.py:_flush():75] Loading settings from /home/lieberze/.config/wandb/settings
2022-03-10 00:15:50,045 INFO    MainThread:7301 [wandb_setup.py:_flush():75] Loading settings from /home/lieberze/DP/Thesis/06_adapter/wandb/settings
2022-03-10 00:15:50,045 INFO    MainThread:7301 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-10 00:15:50,045 INFO    MainThread:7301 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-10 00:15:50,046 INFO    MainThread:7301 [wandb_init.py:_log_setup():386] Logging user logs to /home/lieberze/DP/Thesis/06_adapter/wandb/run-20220310_001550-1wpi08vt/logs/debug.log
2022-03-10 00:15:50,046 INFO    MainThread:7301 [wandb_init.py:_log_setup():387] Logging internal logs to /home/lieberze/DP/Thesis/06_adapter/wandb/run-20220310_001550-1wpi08vt/logs/debug-internal.log
2022-03-10 00:15:50,046 INFO    MainThread:7301 [wandb_init.py:_jupyter_setup():336] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f63ec09a208>
2022-03-10 00:15:50,049 INFO    MainThread:7301 [wandb_init.py:init():420] calling init triggers
2022-03-10 00:15:50,049 INFO    MainThread:7301 [wandb_init.py:init():427] wandb.init called with sweep_config: {}
config: {}
2022-03-10 00:15:50,049 INFO    MainThread:7301 [wandb_init.py:init():471] starting backend
2022-03-10 00:15:50,049 INFO    MainThread:7301 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-10 00:15:50,069 INFO    MainThread:7301 [backend.py:ensure_launched():219] starting backend process...
2022-03-10 00:15:50,087 INFO    MainThread:7301 [backend.py:ensure_launched():225] started backend process with pid: 7335
2022-03-10 00:15:50,089 INFO    MainThread:7301 [wandb_init.py:init():480] backend started and connected
2022-03-10 00:15:50,136 INFO    MainThread:7301 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-03-10 00:15:50,138 INFO    MainThread:7301 [wandb_run.py:_label_probe_notebook():931] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-03-10 00:15:50,138 INFO    MainThread:7301 [wandb_init.py:init():550] updated telemetry
2022-03-10 00:15:50,201 INFO    MainThread:7301 [wandb_init.py:init():581] communicating current version
2022-03-10 00:15:51,948 INFO    MainThread:7301 [wandb_init.py:init():586] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-10 00:15:51,950 INFO    MainThread:7301 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-10 00:15:52,132 INFO    MainThread:7301 [wandb_init.py:init():624] starting run threads in backend
2022-03-10 00:15:57,142 INFO    MainThread:7301 [wandb_run.py:_console_start():1827] atexit reg
2022-03-10 00:15:57,144 INFO    MainThread:7301 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2022-03-10 00:15:57,149 INFO    MainThread:7301 [wandb_run.py:_redirect():1738] Wrapping output streams.
2022-03-10 00:15:57,150 INFO    MainThread:7301 [wandb_run.py:_redirect():1762] Redirects installed.
2022-03-10 00:15:57,151 INFO    MainThread:7301 [wandb_init.py:init():651] run started, returning control to user process
2022-03-10 00:15:59,253 INFO    MainThread:7301 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-10 00:15:59,253 INFO    MainThread:7301 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-10 00:17:03,400 INFO    MainThread:7301 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-10 00:17:03,402 INFO    MainThread:7301 [wandb_run.py:finish():1468] finishing run liebelife/adapter_CV_2x2/1wpi08vt
2022-03-10 00:17:03,406 INFO    MainThread:7301 [jupyter.py:save_history():429] not saving jupyter history
2022-03-10 00:17:03,406 INFO    MainThread:7301 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-10 00:17:03,407 INFO    MainThread:7301 [wandb_init.py:_jupyter_teardown():318] cleaning up jupyter logic
2022-03-10 00:17:03,407 INFO    MainThread:7301 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-03-10 00:17:03,408 INFO    MainThread:7301 [wandb_run.py:_restore():1769] restore
2022-03-10 00:17:03,754 INFO    MainThread:7301 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 880
}

2022-03-10 00:17:03,896 INFO    MainThread:7301 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 880
}

2022-03-10 00:17:04,069 INFO    MainThread:7301 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 880
}

2022-03-10 00:17:04,260 INFO    MainThread:7301 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 10690
}

2022-03-10 00:17:04,363 INFO    MainThread:7301 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 10690
}

2022-03-10 00:17:04,479 INFO    MainThread:7301 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 10690
}

2022-03-10 00:17:04,581 INFO    MainThread:7301 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10690
  total_bytes: 10690
}

2022-03-10 00:17:04,686 INFO    MainThread:7301 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10690
  total_bytes: 10690
}

2022-03-10 00:17:04,788 INFO    MainThread:7301 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10690
  total_bytes: 10690
}

2022-03-10 00:17:04,890 INFO    MainThread:7301 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10690
  total_bytes: 10690
}

2022-03-10 00:17:04,993 INFO    MainThread:7301 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10690
  total_bytes: 10690
}

2022-03-10 00:17:05,095 INFO    MainThread:7301 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10690
  total_bytes: 10690
}

2022-03-10 00:17:05,576 INFO    MainThread:7301 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10690
  total_bytes: 10690
}

2022-03-10 00:17:06,001 INFO    MainThread:7301 [wandb_run.py:_wait_for_finish():1929] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10690
  total_bytes: 10690
}
local_info {
}

2022-03-10 00:17:07,398 INFO    MainThread:7301 [wandb_run.py:_append_files():2194] logging synced files
